# Generated by Django 4.2.7 on 2025-07-11 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = []
